Windows results in NoClassDefFoundError on Launcher because of the format?
git-svn-id: https://svn.jenkins-ci.org/trunk@22273 71c3de6d-444a-0410-be80-ed276b4c234a