Handle AbortException better to avoid error like this:
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to delete directory: C:\files\hudson\workspace\hudson\hudson\main\remoting\target. Reason: Unable to delete file C:\files\hudson\workspace\hudson\hudson\main\remoting\target\remoting-1.304-SNAPSHOT.jar

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31 seconds
[INFO] Finished at: Sun May 10 18:15:33 PDT 2009
[INFO] Final Memory: 25M/48M
[INFO] ------------------------------------------------------------------------
Recording fingerprints
Archiving artifacts
Recording test results
ERROR: Failed to archive JUnit reports
hudson.util.IOException2: remote file operation failed
	at hudson.FilePath.act(FilePath.java:596)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:82)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildStep(AbstractBuild.java:372)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildStep(AbstractBuild.java:360)
	at hudson.model.Build$RunnerImpl.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:345)
	at hudson.model.Run.run(Run.java:943)
	at hudson.model.Build.run(Build.java:112)
	at hudson.model.ResourceController.execute(ResourceController.java:93)
	at hudson.model.Executor.run(Executor.java:119)
Caused by: hudson.AbortException: Test reports were found but none of them are new. Did tests run? 
For example, \files\hudson\workspace\hudson\hudson\main\core\target\surefire-reports\TEST-hudson.BulkChangeTest.xml is 2 days 23 hr old

	at hudson.tasks.junit.TestResult.parse(TestResult.java:134)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:95)
	at hudson.tasks.junit.JUnitResultArchiver$1.invoke(JUnitResultArchiver.java:95)
	at hudson.tasks.junit.JUnitResultArchiver$1.invoke(JUnitResultArchiver.java:82)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:1583)
	at hudson.remoting.UserRequest.perform(UserRequest.java:92)
	at hudson.remoting.UserRequest.perform(UserRequest.java:46)
	at hudson.remoting.Request$2.run(Request.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)

git-svn-id: https://svn.jenkins-ci.org/branches/tool-autoinstallation@17958 71c3de6d-444a-0410-be80-ed276b4c234a